version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - eb/setup
      - run: npm install
      - run:
          name: Deploying
          command: cd backend && eb deploy Weddingapp-env

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: aws
